// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TopLab.Infrastructure.Persistence;

#nullable disable

namespace TopLab.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260828123530_RenamePkColumns")]
    partial class RenamePkColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TopLab.Domain.Accounting.CashMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CashMovementId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("LastModifiedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("ModificationCount")
                        .HasColumnType("int");

                    b.Property<byte>("MovementType")
                        .HasColumnType("tinyint");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("PerformedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("RelatedExternalEntityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RelatedExternalEntityId");

                    b.ToTable("CashMovements");
                });

            modelBuilder.Entity("TopLab.Domain.Attendance.AttendanceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AttendanceRecordId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BreakEndAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("BreakStartAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckInAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CheckOutAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LatenessMinutes")
                        .HasColumnType("int");

                    b.Property<int?>("OvertimeMinutes")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AttendanceRecords");
                });

            modelBuilder.Entity("TopLab.Domain.Billing.PaymentOperation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PaymentOperationId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<decimal?>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsExtraCharge")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVoided")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("LastModifiedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("ModificationCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("OperationAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte>("OperationType")
                        .HasColumnType("tinyint");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("ReceivedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("PaymentOperations");
                });

            modelBuilder.Entity("TopLab.Domain.Billing.PriceList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PriceListId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("PriceLists");
                });

            modelBuilder.Entity("TopLab.Domain.Billing.PriceListItem", b =>
                {
                    b.Property<int>("PriceListId")
                        .HasColumnType("int");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PriceListId", "TestId");

                    b.ToTable("PriceListItems");
                });

            modelBuilder.Entity("TopLab.Domain.ExternalEntities.ExternalEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ExternalEntityId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<decimal?>("DiscountOrCommissionPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<byte>("EntityType")
                        .HasColumnType("tinyint");

                    b.Property<string>("Fax")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("GeneratedIdCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("LastModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("LastModifiedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("ModificationCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("PriceListId")
                        .HasColumnType("int");

                    b.Property<string>("ResponsiblePersonName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ResponsiblePersonPhone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("EntityType");

                    b.HasIndex("PriceListId");

                    b.ToTable("ExternalEntities");
                });

            modelBuilder.Entity("TopLab.Domain.Patients.MedicalConditionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MedicalConditionTypeId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("Category")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("MedicalConditionTypes");
                });

            modelBuilder.Entity("TopLab.Domain.Patients.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PatientId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("AccountType")
                        .HasColumnType("tinyint");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<byte>("AgeUnit")
                        .HasColumnType("tinyint");

                    b.Property<int>("AgeValue")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("FastingHours")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsFastingIndicated")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVip")
                        .HasColumnType("bit");

                    b.Property<string>("LabId")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("LastModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("LastModifiedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("ModificationCount")
                        .HasColumnType("int");

                    b.Property<string>("NationalId")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("PickupDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("RecentContrastImaging")
                        .HasColumnType("bit");

                    b.Property<int?>("ReferralEntityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegistrationDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Sex")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TreatingDoctorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FullName");

                    b.HasIndex("LabId");

                    b.HasIndex("NationalId");

                    b.HasIndex("RegistrationDateUtc");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("TopLab.Domain.Patients.PatientMedicalCondition", b =>
                {
                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("MedicalConditionTypeId")
                        .HasColumnType("int");

                    b.HasKey("PatientId", "MedicalConditionTypeId");

                    b.ToTable("PatientMedicalConditions");
                });

            modelBuilder.Entity("TopLab.Domain.Patients.PatientPhoneNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PatientPhoneNumberId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<byte>("SortOrder")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("PhoneNumber");

                    b.ToTable("PatientPhoneNumbers");
                });

            modelBuilder.Entity("TopLab.Domain.Patients.PatientTitle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PatientTitleId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("TitleText")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("PatientTitles");
                });

            modelBuilder.Entity("TopLab.Domain.Results.CultureAntibioticResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CultureAntibioticResultId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AntibioticId")
                        .HasColumnType("int");

                    b.Property<int>("PatientTestId")
                        .HasColumnType("int");

                    b.Property<byte>("SensitivityCategory")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("AntibioticId");

                    b.HasIndex("PatientTestId");

                    b.ToTable("CultureAntibioticResults");
                });

            modelBuilder.Entity("TopLab.Domain.Results.CultureResult", b =>
                {
                    b.Property<int>("PatientTestId")
                        .HasColumnType("int");

                    b.Property<string>("ColonyCount")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CultureCondition")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OrganismA")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("OrganismB")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("OrganismC")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Sample")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PatientTestId");

                    b.ToTable("CultureResults");
                });

            modelBuilder.Entity("TopLab.Domain.Results.PatientTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PatientTestId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeliveredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeliveredByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EnteredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EnteredByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExportedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsBlood")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCsf")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelivered")
                        .HasColumnType("bit");

                    b.Property<bool>("IsExported")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrinted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReviewed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSampleDrawn")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSemen")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStool")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTakenOutsideLab")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUrine")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("LastModifiedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastPrintedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LastPrintedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("ModificationCount")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<decimal>("PriceAtOrderTime")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PrintCount")
                        .HasColumnType("int");

                    b.Property<int?>("ResultFlag")
                        .HasColumnType("tinyint");

                    b.Property<string>("ResultValue")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReviewedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SampleDrawnAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("TestId");

                    b.HasIndex("IsReviewed", "IsPrinted", "IsDelivered");

                    b.ToTable("PatientTests");
                });

            modelBuilder.Entity("TopLab.Domain.Results.ProfileResultItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProfileResultItemId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnalyteName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("Flag")
                        .HasColumnType("tinyint");

                    b.Property<bool>("IsPrinted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<int>("PatientTestId")
                        .HasColumnType("int");

                    b.Property<string>("ResultValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Unit")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("PatientTestId");

                    b.ToTable("ProfileResultItems");
                });

            modelBuilder.Entity("TopLab.Domain.SentOutSamples.SentOutSample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SentOutSampleId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CostPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("ExternalLabEntityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("LastModifiedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("ModificationCount")
                        .HasColumnType("int");

                    b.Property<decimal>("PatientPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PatientTestId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ExternalLabEntityId");

                    b.HasIndex("PatientTestId");

                    b.ToTable("SentOutSamples");
                });

            modelBuilder.Entity("TopLab.Domain.SentOutSamples.SentOutSamplePayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SentOutSamplePaymentId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountPaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PaidAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("PerformedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("SentOutSampleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SentOutSampleId");

                    b.ToTable("SentOutSamplePayments");
                });

            modelBuilder.Entity("TopLab.Domain.Settings.EnvelopePrintItemPosition", b =>
                {
                    b.Property<string>("ItemName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<decimal>("LeftOffsetCm")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("TopOffsetCm")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("ItemName");

                    b.ToTable("EnvelopePrintItemPositions");

                    b.HasData(
                        new
                        {
                            ItemName = "Name",
                            IsEnabled = true,
                            LeftOffsetCm = 1.0m,
                            TopOffsetCm = 1.0m
                        },
                        new
                        {
                            ItemName = "Code",
                            IsEnabled = true,
                            LeftOffsetCm = 1.0m,
                            TopOffsetCm = 2.0m
                        },
                        new
                        {
                            ItemName = "ReferralEntity",
                            IsEnabled = true,
                            LeftOffsetCm = 1.0m,
                            TopOffsetCm = 3.0m
                        },
                        new
                        {
                            ItemName = "Date",
                            IsEnabled = true,
                            LeftOffsetCm = 1.0m,
                            TopOffsetCm = 4.0m
                        });
                });

            modelBuilder.Entity("TopLab.Domain.Settings.EnvelopeSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("EnvelopeSettingsId");

                    b.Property<byte>("HeaderFooterMode")
                        .HasColumnType("tinyint");

                    b.Property<bool>("SuppressCaptions")
                        .HasColumnType("bit");

                    b.Property<decimal>("TopMarginCm")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.ToTable("EnvelopeSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HeaderFooterMode = (byte)0,
                            SuppressCaptions = false,
                            TopMarginCm = 3.0m
                        });
                });

            modelBuilder.Entity("TopLab.Domain.Settings.PrinterAssignment", b =>
                {
                    b.Property<byte>("OutputType")
                        .HasColumnType("tinyint");

                    b.Property<string>("PrinterName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("OutputType");

                    b.ToTable("PrinterAssignments");

                    b.HasData(
                        new
                        {
                            OutputType = (byte)0,
                            PrinterName = "Reports"
                        },
                        new
                        {
                            OutputType = (byte)1,
                            PrinterName = "Barcode"
                        },
                        new
                        {
                            OutputType = (byte)2,
                            PrinterName = "Envelope"
                        },
                        new
                        {
                            OutputType = (byte)3,
                            PrinterName = "Receipt"
                        });
                });

            modelBuilder.Entity("TopLab.Domain.Settings.ReceiptSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ReceiptSettingsId");

                    b.Property<bool>("CashierPrinterEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<byte>("HeaderFooterMode")
                        .HasColumnType("tinyint");

                    b.Property<TimeOnly?>("PickupTimeDefault")
                        .HasColumnType("time");

                    b.Property<bool>("PrintOnce")
                        .HasColumnType("bit");

                    b.Property<byte>("TestDetailDisplayMode")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("TopMarginCm")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.ToTable("ReceiptSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CashierPrinterEnabled = false,
                            Currency = "L.E.",
                            HeaderFooterMode = (byte)0,
                            PrintOnce = false,
                            TestDetailDisplayMode = (byte)1,
                            TopMarginCm = 1.0m
                        });
                });

            modelBuilder.Entity("TopLab.Domain.Settings.ReportSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ReportSettingsId");

                    b.Property<bool>("DoctorSignatureEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("FooterColor")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("HeaderColor")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<byte>("HeaderFooterMode")
                        .HasColumnType("tinyint");

                    b.Property<bool>("HistoryAutoDisplayEnabled")
                        .HasColumnType("bit");

                    b.Property<byte>("HistorySortMode")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("PageMarginBottomCm")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PageMarginLeftCm")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<byte>("PaperSize")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("ReportTopSpaceCm")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.ToTable("ReportSettings", t =>
                        {
                            t.HasCheckConstraint("CK_ReportSettings_TopSpace", "[ReportTopSpaceCm] <= 8");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DoctorSignatureEnabled = false,
                            HeaderFooterMode = (byte)0,
                            HistoryAutoDisplayEnabled = true,
                            HistorySortMode = (byte)0,
                            PageMarginBottomCm = 1.0m,
                            PageMarginLeftCm = 1.0m,
                            PaperSize = (byte)0,
                            ReportTopSpaceCm = 2.0m
                        });
                });

            modelBuilder.Entity("TopLab.Domain.Settings.SystemSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("SystemSettingsId");

                    b.Property<bool>("AutoReviewAndComplete")
                        .HasColumnType("bit");

                    b.Property<bool>("DailyBackupEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("DailyBackupPath")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<byte>("DefaultAccountType")
                        .HasColumnType("tinyint");

                    b.Property<bool>("DisableAutoTitleInsertion")
                        .HasColumnType("bit");

                    b.Property<bool>("EnablePatientNameSearchAssist")
                        .HasColumnType("bit");

                    b.Property<bool>("PrintAccountInsteadOfDateOnReport")
                        .HasColumnType("bit");

                    b.Property<bool>("PrintDateTimeOnTubeBarcode")
                        .HasColumnType("bit");

                    b.Property<bool>("PrintFileExternalBarcode")
                        .HasColumnType("bit");

                    b.Property<bool>("PrintLabIdInsteadOfPatientId")
                        .HasColumnType("bit");

                    b.Property<byte>("ResultScreenAccountDisplayMode")
                        .HasColumnType("tinyint");

                    b.Property<bool>("SaveTreatingDoctorOnlyFromEntityWindow")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("SystemSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AutoReviewAndComplete = false,
                            DailyBackupEnabled = false,
                            DefaultAccountType = (byte)0,
                            DisableAutoTitleInsertion = false,
                            EnablePatientNameSearchAssist = false,
                            PrintAccountInsteadOfDateOnReport = false,
                            PrintDateTimeOnTubeBarcode = false,
                            PrintFileExternalBarcode = false,
                            PrintLabIdInsteadOfPatientId = false,
                            ResultScreenAccountDisplayMode = (byte)0,
                            SaveTreatingDoctorOnlyFromEntityWindow = false
                        });
                });

            modelBuilder.Entity("TopLab.Domain.Tests.Antibiotic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AntibioticId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsChildrenFlagged")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPregnancyFlagged")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Antibiotics");
                });

            modelBuilder.Entity("TopLab.Domain.Tests.CultureAntibioticAttachment", b =>
                {
                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.Property<int>("AntibioticId")
                        .HasColumnType("int");

                    b.HasKey("TestId", "AntibioticId");

                    b.ToTable("CultureAntibioticAttachments");
                });

            modelBuilder.Entity("TopLab.Domain.Tests.CustomGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CustomGroupId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("CustomGroups");
                });

            modelBuilder.Entity("TopLab.Domain.Tests.CustomGroupItem", b =>
                {
                    b.Property<int>("CustomGroupId")
                        .HasColumnType("int");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CustomGroupId", "TestId");

                    b.ToTable("CustomGroupItems");
                });

            modelBuilder.Entity("TopLab.Domain.Tests.ReferenceRange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReferenceRangeId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgeMax")
                        .HasColumnType("int");

                    b.Property<int>("AgeMin")
                        .HasColumnType("int");

                    b.Property<byte>("AgeUnit")
                        .HasColumnType("tinyint");

                    b.Property<string>("HighComment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LowComment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("MaxValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("MinValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("Sex")
                        .HasColumnType("tinyint");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TestId");

                    b.ToTable("ReferenceRanges");
                });

            modelBuilder.Entity("TopLab.Domain.Tests.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TestId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CompletionDurationMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCultureType")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSentOut")
                        .HasColumnType("bit");

                    b.Property<decimal?>("LabToLabPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("LastModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("LastModifiedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("ModificationCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("PatientPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReceiptName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ReportName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte>("ResultKind")
                        .HasColumnType("tinyint");

                    b.Property<decimal?>("SentOutCostPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TestGroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("TestGroupId");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("TopLab.Domain.Tests.TestComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TestCommentId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TestId");

                    b.ToTable("TestComments");
                });

            modelBuilder.Entity("TopLab.Domain.Tests.TestGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TestGroupId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("TestGroups");
                });

            modelBuilder.Entity("TopLab.Domain.Tests.WorkGroupLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("WorkGroupLogId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("WorkGroupLogs");
                });

            modelBuilder.Entity("TopLab.Domain.Tests.WorkGroupLogItem", b =>
                {
                    b.Property<int>("WorkGroupLogId")
                        .HasColumnType("int");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.HasKey("WorkGroupLogId", "TestId");

                    b.ToTable("WorkGroupLogItems");
                });

            modelBuilder.Entity("TopLab.Domain.Users.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PermissionId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "ADD_EDIT_PATIENT",
                            Description = "Add and edit patient data"
                        },
                        new
                        {
                            Id = 2,
                            Code = "EDIT_RESULTS",
                            Description = "Enter and edit patient test results"
                        },
                        new
                        {
                            Id = 3,
                            Code = "REVIEW_RESULTS",
                            Description = "Review and edit patient test results"
                        },
                        new
                        {
                            Id = 4,
                            Code = "PRINT_RESULTS",
                            Description = "Print patient results"
                        },
                        new
                        {
                            Id = 5,
                            Code = "BLOCK_PRINT_ON_BALANCE",
                            Description = "Block printing when balance remains"
                        },
                        new
                        {
                            Id = 6,
                            Code = "DELIVER_RESULTS",
                            Description = "Deliver results"
                        },
                        new
                        {
                            Id = 7,
                            Code = "DISCOUNT_LIMIT",
                            Description = "Discount limit"
                        },
                        new
                        {
                            Id = 8,
                            Code = "PRINT_WORKSHEET",
                            Description = "Print worksheet and Log"
                        },
                        new
                        {
                            Id = 9,
                            Code = "DELETE_PATIENT",
                            Description = "Delete patients"
                        },
                        new
                        {
                            Id = 10,
                            Code = "EDIT_SYSTEM_SETTINGS",
                            Description = "Edit system and test settings"
                        },
                        new
                        {
                            Id = 11,
                            Code = "CASH_DISBURSE_DEPOSIT",
                            Description = "Cash disbursement and deposit"
                        },
                        new
                        {
                            Id = 12,
                            Code = "STATISTICS",
                            Description = "Statistics"
                        },
                        new
                        {
                            Id = 13,
                            Code = "PT_AUDIT_ACCESS",
                            Description = "P/T audit access"
                        });
                });

            modelBuilder.Entity("TopLab.Domain.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("BlockPrintOnRemainingBalance")
                        .HasColumnType("bit");

                    b.Property<int?>("BreakDurationMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<decimal>("DiscountLimitPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("HasBreakPeriod")
                        .HasColumnType("bit");

                    b.Property<string>("InternalWindowsPasswordHash")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsAbsolutePermission")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("LastModifiedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("ModificationCount")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<TimeOnly?>("WorkEndTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("WorkStartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TopLab.Domain.Users.UserPermissionGrant", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "PermissionId");

                    b.ToTable("UserPermissionGrants");
                });

            modelBuilder.Entity("TopLab.Domain.Accounting.CashMovement", b =>
                {
                    b.HasOne("TopLab.Domain.ExternalEntities.ExternalEntity", null)
                        .WithMany()
                        .HasForeignKey("RelatedExternalEntityId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("TopLab.Domain.Attendance.AttendanceRecord", b =>
                {
                    b.HasOne("TopLab.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TopLab.Domain.Billing.PaymentOperation", b =>
                {
                    b.HasOne("TopLab.Domain.Patients.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TopLab.Domain.Billing.PriceListItem", b =>
                {
                    b.HasOne("TopLab.Domain.Billing.PriceList", null)
                        .WithMany("Items")
                        .HasForeignKey("PriceListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TopLab.Domain.ExternalEntities.ExternalEntity", b =>
                {
                    b.HasOne("TopLab.Domain.Billing.PriceList", null)
                        .WithMany()
                        .HasForeignKey("PriceListId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("TopLab.Domain.Patients.PatientMedicalCondition", b =>
                {
                    b.HasOne("TopLab.Domain.Patients.Patient", null)
                        .WithMany("MedicalConditions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TopLab.Domain.Patients.PatientPhoneNumber", b =>
                {
                    b.HasOne("TopLab.Domain.Patients.Patient", null)
                        .WithMany("PhoneNumbers")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TopLab.Domain.Results.CultureAntibioticResult", b =>
                {
                    b.HasOne("TopLab.Domain.Tests.Antibiotic", null)
                        .WithMany()
                        .HasForeignKey("AntibioticId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TopLab.Domain.Results.CultureResult", null)
                        .WithMany()
                        .HasForeignKey("PatientTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TopLab.Domain.Results.CultureResult", b =>
                {
                    b.HasOne("TopLab.Domain.Results.PatientTest", null)
                        .WithOne()
                        .HasForeignKey("TopLab.Domain.Results.CultureResult", "PatientTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TopLab.Domain.Results.PatientTest", b =>
                {
                    b.HasOne("TopLab.Domain.Patients.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TopLab.Domain.Tests.Test", null)
                        .WithMany()
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TopLab.Domain.Results.ProfileResultItem", b =>
                {
                    b.HasOne("TopLab.Domain.Results.PatientTest", null)
                        .WithMany()
                        .HasForeignKey("PatientTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TopLab.Domain.SentOutSamples.SentOutSample", b =>
                {
                    b.HasOne("TopLab.Domain.ExternalEntities.ExternalEntity", null)
                        .WithMany()
                        .HasForeignKey("ExternalLabEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TopLab.Domain.Results.PatientTest", null)
                        .WithMany()
                        .HasForeignKey("PatientTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TopLab.Domain.SentOutSamples.SentOutSamplePayment", b =>
                {
                    b.HasOne("TopLab.Domain.SentOutSamples.SentOutSample", null)
                        .WithMany()
                        .HasForeignKey("SentOutSampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TopLab.Domain.Tests.CustomGroupItem", b =>
                {
                    b.HasOne("TopLab.Domain.Tests.CustomGroup", null)
                        .WithMany("Items")
                        .HasForeignKey("CustomGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TopLab.Domain.Tests.ReferenceRange", b =>
                {
                    b.HasOne("TopLab.Domain.Tests.Test", null)
                        .WithMany()
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TopLab.Domain.Tests.Test", b =>
                {
                    b.HasOne("TopLab.Domain.Tests.TestGroup", null)
                        .WithMany()
                        .HasForeignKey("TestGroupId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("TopLab.Domain.Tests.TestComment", b =>
                {
                    b.HasOne("TopLab.Domain.Tests.Test", null)
                        .WithMany()
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TopLab.Domain.Tests.WorkGroupLogItem", b =>
                {
                    b.HasOne("TopLab.Domain.Tests.WorkGroupLog", null)
                        .WithMany("Items")
                        .HasForeignKey("WorkGroupLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TopLab.Domain.Users.UserPermissionGrant", b =>
                {
                    b.HasOne("TopLab.Domain.Users.User", null)
                        .WithMany("PermissionGrants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TopLab.Domain.Billing.PriceList", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("TopLab.Domain.Patients.Patient", b =>
                {
                    b.Navigation("MedicalConditions");

                    b.Navigation("PhoneNumbers");
                });

            modelBuilder.Entity("TopLab.Domain.Tests.CustomGroup", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("TopLab.Domain.Tests.WorkGroupLog", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("TopLab.Domain.Users.User", b =>
                {
                    b.Navigation("PermissionGrants");
                });
#pragma warning restore 612, 618
        }
    }
}
